site_name: Calculation Tools Documentation
theme:
  name: 'material'

nav:
  - Home: index.md

  - Getting Started:
      - Prerequisites:
          - Old Version Prerequisites: old_version/prerequisites.md
          - Modified Version Prerequisites: modified_version/prerequisites.md
      - Setup:
          - Old Version Setup: old_version/setup.md
          - Modified Version Setup: modified_version/setup.md

  - Code Structure:
      - Overview: code_structure/overview.md
      - Old Version: code_structure/old_version.md
      - Modified Version: code_structure/modified_version.md

  - Deployment & CI/CD:
      - General Instructions: deployment/general.md
      - Azure DevOps Setup: deployment/azure_devops.md
      - AWS Deployment & Pipeline: deployment/aws_pipeline.md

  - Cloud Deployment:
      - Requirements: cloud/deployment_guide.md
      - Deploying on Azure: cloud/azure_deployment_guide.md
      - Deploying on AWS: cloud/aws_deployment_guide.md

  - Usage:
      - Usage Examples: usage/old_version.md

  - Development Documentation:
      - Technical Architecture: development/architecture.md
      - Codebase Structure: development/codebase_structure.md

  - Maintenance & Troubleshooting:
      - Maintenance Plan: maintenance/plan.md
      - Troubleshooting:  maintenance/troubleshooting_guide.md
      

  - Contribution:
      - Guidelines: contribution/guidelines.md

  - Improvements:
      - Detailed Report on Proposed Improvements: improvements/report.md

  - Changelog: changelog.md